name: Build and Publish to Registry

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - uses: actions/checkout@v3
      - name: Get Dockerfile
        run: cp ./docker/Dockerfile Dockerfile

      - id: push-image
        name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/nestjs-backend-microservice:latest
          push: true

      - name: Image digest
        run: 'echo Digest: ${{ steps.push-image.outputs.digest }}'
