name: Docker Image CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Dockerfile
        run: cd /home/runner/work/nestjs-backend-microservice/nestjs-backend-microservice
        
      - name: Get Dockerfile
        run: ls -la
        
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build ./docker --tag nestjs-backend-microservice:$(date +%s)
