name: Docker Image CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Dockerfile
        run: cp ./docker/Dockerfile Dockerfile

      - id: buildx
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag nestjs-backend-microservice:$(date +%s)

      - name: Image digest
        run: 'echo Digest: ${{ steps.push-image.outputs.digest }}'
