name: E2E test

on: [push]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nestjs
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./
      - name: Run E2E tests
        run: |
          cp .env.example .env
          npm run build
          npm run test:e2e
        env:
          CI: 'true'
          PORT: 3000
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nestjs
          DATABASE_URL: postgres://user:password@localhost:${{ job.services.postgres.ports[5432] }}/nestjs
